# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: STOP_APP
    build: .
    command: flask run -h 0.0.0.0
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/STOP_APP.db
    volumes:
      - ./STOP_APP:/code/STOP_APP
      - ./db/:/db/
    ports:
      - "5000:5000"
